# Generated by Django 3.2.5 on 2022-07-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('course', models.CharField(choices=[('BBA', 'BBA'), ('Bcom', 'Bcom'), ('Law', 'Law'), ('BA.Psy', 'BA.Psychology'), ('BE', 'Engineering')], max_length=8)),
            ],
        ),
    ]
