# Generated by Django 3.2.5 on 2022-07-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
