# Generated by Django 3.2.5 on 2022-07-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootsapi', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='EventUser',
        ),
    ]
